apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-play
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wr-fmbah/argo-play.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo-play-ns

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true