---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-initcontainer-sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wr-fmbah/argo-play.git
    targetRevision: HEAD
    path: dev/nginx-initcontainer-sample/
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx-initcontainer-sample
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true