---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wr-fmbah/argo-play.git
    targetRevision: HEAD
    path: dev/podinfo-app/
  destination: 
    server: https://kubernetes.default.svc
    namespace: podinfo-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true