namePrefix: dev-
commonLabels:
  env: dev
commonAnnotations:
  typeofApp: htmlApp
bases:
- ../../base
namespace: kustomize-namespace
patchesStrategicMerge:
- deployment.yaml
- service.yaml
secretGenerator:
- name: dummy
  files: 
  - password.txt
