apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostblog-app
  namespace: ghostblog-ns
  labels:
    app: ghostblog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghostblog-app
  template:
    metadata:
      labels:
        app: ghostblog-app
    spec:
      containers:
      - name: ghostblog-app
        image: phelun/ghost-init:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
