apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-env-ghostblog
  namespace: staging-env-ghostblog
  labels:
    app: staging-env-ghostblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staging-env-ghostblog
  template:
    metadata:
      labels:
        app: staging-env-ghostblog
    spec:
      containers:
      - name: staging-env-ghostblog
        image: 658951324167.dkr.ecr.eu-west-1.amazonaws.com/gitops-in-action-gblog-proj:v0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
