apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy: {}
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: singharunk/webserver:v3
        name: portfolio
        resources: {}

